
for alpha = Alpha
    for delta = Delta
        DESTINATION_FOLDER = WYNIKI_FOLDER + ...
            "\a-" + string(alpha) + ...
            "_d-" + string(delta) + ...
            "_e1-" + string(epsilon{1}) + ...
            "_e2-" + string(epsilon{2}) + "\";
        mkdir(DESTINATION_FOLDER)
        TunePID(alpha, delta, epsilon, QI, model_file, DESTINATION_FOLDER, metoda_optymalizacji)
    end
end